# Generated by Django 5.1.3 on 2024-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_djangomodelclass_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangomodelclass',
            name='file_path_field',
            field=models.FilePathField(path='files'),
        ),
    ]
